### PR TITLE
Wip/bewest/dev

### PR DESCRIPTION
**Pull request by bewest**
# Dev Branch Nightscout Connect

* sundry fixes
* Libre
  * version update, Libre 3
  * [x] Libre works :+1: 
* Glooko remaining issues?
* Dexcom server name update.
* Medtronic

## Minimed Carelink Updates
* robust to more errors
* include some pump and treatment events
* more sensitive to UA string

### CODE REVIEW

**Comment by bewest** [comment]
@AndyLow91, I've adjusted to correctly use the browser string for URLs truly expecting a browser.  The Nightscout Connect attribution is also included in the browser UA string.  Finally, an extra UUID was added based on feedback from https://github.com/nightscout/minimed-connect-to-nightscout/pull/46.  Instead of doing the latter, it may prove better to generate 6 - 8 random characters and append that instead.

**Comment by bewest** [comment]
Note, the Medtronic implementation does not implement the refresh logic.  I'm not sure how the refresh logic is supposed to work, but it could play a role in reducing the need to overflow the rate on calling consent method, as it's probably expected to refresh in production.

**Comment by sbc2280** [comment]
> Steps to get this working? #3

I think this may work for refresh token

https://github.com/anguriskit24/CareLinkJavaClient/tree/feature/get-new-auth-token

**Comment by bewest** [comment]
Ah, I see they add the `locale` and `country`  [query parameters](https://github.com/anguriskit24/CareLinkJavaClient/blob/22defbd961a5092c7ed40f3f64adc0170928df39/src/main/java/info/nightscout/medtronic/carelink/client/CareLinkClient.java#L308-L310), same as the log in requires.  I will try this out.

**Comment by bewest** [comment]
Thanks, @sbc2280.  I don't know why, but refreshing the session is so much more satisfying than creating a new one.

**Pull request merged**
